//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1_2.TelerikAcademyEmployees
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_logged_in_today
    {
        public string username { get; set; }
    }
}
